name: Trigger auto deployment for oniturlcautp-tapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/oniturlcautp-tapi-AutoDeployTrigger-17bf2bdb-87e8-43eb-925e-fd4a3aefded0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ONITURLCAUTPTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ONITURLCAUTPTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ONITURLCAUTPTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: oneiro-hdd8aqdbhufwh7h7.azurecr.io
          registryUsername: ${{ secrets.ONITURLCAUTPTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ONITURLCAUTPTAPI_REGISTRY_PASSWORD }}
          containerAppName: oniturlcautp-tapi
          resourceGroup: oniturlrgutp
          imageToBuild: oneiro-hdd8aqdbhufwh7h7.azurecr.io/oniturlcautp-tapi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


